framework:
    default_locale: fr
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
            - fr
        providers:
            yaml_file:
                # Define translation message directories for each locale
                locales:
                    fr: '%kernel.project_dir%/translations/messages.fr.yml'
                    en: '%kernel.project_dir%/translations/messages.en.yml'

